### ISSUE TITLE
about.html linked in to open new window

### ISSUE THREAD

**Issue by lisaar** [croydondias/gapsummit-site#3]
linked in to open in new window, icon to be located in place of about each founder text

**Comment by croydondias** [comment]
Can you clarify the second bit please. Do you want the LinkedIn icon to the end of the about text?

> Lisa Altmann-Richer
> COO, GapSummit Cambridge
> 
> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec enim sapien. Aliquam erat volutpat. Quisque eu ante at tortor imperdiet gravida nec sed turpis. Phasellus augue augue. [Linkedin icon here]

**Comment by lisaar** [comment]
yep, instead on the lorem ipsum text can you put the linked in icon there. so no lorem ipsum text at all

Lisa Altmann-Richer
COO, GapSummit Cambridge
[Linkedin icon here]

thanks

**Comment by croydondias** [comment]
Does this look good to you?
https://dl.dropboxusercontent.com/u/833721/gapsummit-site/cambridge/about.html

**Comment by lisaar** [comment]
yes perfect thanks
